# Google Cloud Build configuration with automatic Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ema-retest-alerts:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ema-retest-alerts:$COMMIT_SHA']

  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/ema-retest-alerts:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/ema-retest-alerts:latest']

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ema-retest-alerts:latest']

  # Clear secrets from Cloud Run service first
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services update ema-retest-alerts \
          --region=asia-south1 \
          --clear-secrets || echo "No secrets to clear or service doesn't exist yet"

  # Deploy to Cloud Run with environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ema-retest-alerts'
      - '--image=gcr.io/$PROJECT_ID/ema-retest-alerts:latest'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--memory=1Gi'
      - '--timeout=540'
      - '--max-instances=1'
      - '--cpu=2'
      - '--set-env-vars=TELEGRAM_BOT_TOKEN=8163995879:AAHEnG-mAxont26F1mwUfOHGv-NJ1iZWkao,TELEGRAM_CHAT_ID=-1002343316074'

images:
  - 'gcr.io/$PROJECT_ID/ema-retest-alerts:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ema-retest-alerts:latest'

# Use cloud logging when service account is specified
options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

